### PR TITLE
Fix #3: Make sidebar fixed, collapsible and responsive

### LINKED ISSUE #3: make the sidebar not move with the main content. also make the sidebar collapsible

### PR DESCRIPTION
**Pull request by akshit2434**
#### Summary of Changes
- Made the sidebar stay fixed despite scrolling
- Made the sidebar collapsible with a button toggle.
- Made UI responsive for all screen sizes
- Made sure no UI bugs are present.
- Added sidenav button for mobile

#### Preview

https://github.com/user-attachments/assets/73880d6a-baec-4177-9078-adba2eb45c72

### CODE REVIEW

**Comment by codeblech** [comment]
this looks good 
can you make the sidebar totally disappear for mobile screens. for mobile screens, it should show just the button and not the whole vertical strip.
that would be better right?

**Comment by akshit2434** [comment]
@codeblech Yup, just implemented it. Please check it out

**Comment by codeblech** [comment]
Looks great! 
A tiny design issue is the size of the heading "Image Gallery". It should be a little bigger and match the size of the menu button. We can even make that heading change according to the opened page.

Would you like to do those changes in this PR or another one? totally upto you

**Comment by akshit2434** [comment]
Thanks for the feedback! 😊
I think it would be best to open a new PR for the additional changes to keep each set of modifications focused and manageable. I'll go ahead and make the adjustments in a new branch and submit a separate PR shortly.

**Comment by akshit2434** [comment]
**Preview**

https://github.com/user-attachments/assets/6940e7a6-8b59-458a-af9c-7b9b3b986171

**Pull request merged**
